### ISSUE TITLE
☂️ Graphene v3

### ISSUE THREAD

**Issue by jkimbo** [graphql-python/graphene#1127]
This issue is to track v3 of Graphene which will contain some breaking changes.

## Breaking changes

* Upgrade to graphql-core to v3 which brings feature parity with GraphQL.js v14.6.0
* Drop support for Python v2
* Schema type changes
* "Backends" have been removed
* Switch arguments from `type` to `type_` since `type` is a builtin: https://github.com/graphql-python/graphene/pull/738
* Upgrade to graphql-core v.3.1 which corresponds to GraphQL.js v15 (will be released soon).
* Change enum behaviour: https://github.com/graphql-python/graphene/pull/1153
* Remove `to_const` function

## TODO

* [x] Write up some proper release notes: https://github.com/graphql-python/graphene/wiki/v3-release-notes
* [x] Merge https://github.com/graphql-python/graphene/pull/1111
* [x] Switch arguments from `type` to `type_` since `type` is a builtin: https://github.com/graphql-python/graphene/pull/738
* [x] Remove `to_const` function: #1212 
* [x] Change enum behaviour: https://github.com/graphql-python/graphene/pull/1153
* [x] Set minimum graphql-core version to v3.1 https://github.com/graphql-python/graphene/pull/1215
* [x] Upgrade [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy) to v3 [WIP](https://github.com/graphql-python/graphene-sqlalchemy/pull/306)
* [x] Upgrade [graphene-mongo](https://github.com/graphql-python/graphene-mongo) to v3 [WIP](https://github.com/graphql-python/graphene-mongo/pull/155)

**Comment by dashmug** [comment]
May I suggest to use GraphiQL Explorer instead of just GraphiQL?

* https://github.com/OneGraph/graphiql-explorer 
* https://github.com/OneGraph/graphiql-explorer-example/tree/master/src

**Comment by jkimbo** [comment]
@dashmug graphene doesn't specify with version of graphiql you use. All you have to do is host GraphiQL yourself and point it at the grapqhl endpoint and it will work.

**Comment by AlecRosenbaum** [comment]
What is the release schedule for v3?

It looks like graphene is currently in beta 2, but what other revisions will there be before a non-beta release? How stable is the current beta? For new projects which version should be used?

**Comment by radekwlsk** [comment]
> What is the release schedule for v3?
> 
> It looks like graphene is currently in beta 2, but what other revisions will there be before a non-beta release? How stable is the current beta? For new projects which version should be used?

AFAIK all that is left to do are proper release notes. I was supposed to help with that but unfortunately I couldn't find time for that this week.

If you would like to help feel free to start working on draft of said notes.

I hope to spend some time on that this weekend, but no promises.

**Comment by DoctorJohn** [comment]
If I interpret the initial comment correctly, the following tasks are left to do (correct me if I'm wrong):

- [ ] Merge #738 
- [ ] Merge #775 
- [ ] Upgrade to [graphql-core v.3.1](https://github.com/graphql-python/graphql-core/releases/)
- [ ] Write up release notes

The master branch being version 3, I guess it's time to merge or properly close #738 and #755. @jkimbo you created on of these PRs and reviewed the other one. Would you mind taking a look at these?

For the graphql-core update, we need to take a look at their changelog(s) and at graphenes tests. (I'll take a look at this).

Last but not least the release notes. I'd imagine them similar to the previous ones ([v1](https://github.com/graphql-python/graphene/blob/master/UPGRADE-v1.0.md), [v2](https://github.com/graphql-python/graphene/blob/master/UPGRADE-v2.0.md)). They should cover all changes listed in the initial issue. One might need to look trough v3 commits to properly cover schema type changes.

**Comment by jkimbo** [comment]
@DoctorJohn I came to the conclusion that #775 is not actually needed (reasons here: https://github.com/graphql-python/graphene/pull/775#issuecomment-648866297). Also #738 needs to be brought up to date with master because it's quite old. @radekwlsk @DoctorJohn if either of you could help with that that would be great.

Other than that that list looks right, I've updated the description to include them.

**Comment by jkimbo** [comment]
Also I'm going to try and find some time this week to finish #1153 but no promises unfortunately.

**Comment by jkimbo** [comment]
https://github.com/graphql-python/graphene/pull/1153 is ready for review now. If anyone has the time to take a look it would be most appreciated.

**Comment by jkimbo** [comment]
Ok #1153 has been merged and I've written up some release notes: https://github.com/graphql-python/graphene/wiki/v3-release-notes

If anyone is able to try out the latest beta in their projects that would be very helpful. Otherwise I think we should aim to release v3 in the next couple of weeks.

**Comment by AlecRosenbaum** [comment]
We've been running `graphene==3.0b2` in production since mid to late June without any major issues. Only a small number of our internal APIs have been migrated to use graphql (from REST), but it still does see regular usage.

We previously were using the `graphql-core` library directly on v2. We updated from v2 to v3, then migrated all of that to `graphene` v3 without any major issues.

@jkimbo Thank you for all the work you've done on this project!

**Comment by radekwlsk** [comment]
I've prepared migration of our project to `graphene`/`graphene-django`/`graphql-core` v3 from v2. No bigger issues there, mainly with new fixed Enums and more low-level stuff that simple projects shouldn't touch (for example our own pagination with filtering not using Relay, custom scalar types and custom Mutation base).

We plan to start testing it on dev or staging environment soon, mainly to check the performance bump from #1157.

Once we do that I will let you know @jkimbo if there were any issues or bugs found.

**Comment by hyusetiawan** [comment]
is V3 backward compatible with third-party or even first-party plugins such as:
https://github.com/graphql-python/graphql-ws
https://github.com/tfoxy/graphene-django-optimizer
?

**Comment by jkimbo** [comment]
Thanks @AlecRosenbaum @radekwlsk , good to know that you haven't encountered any issues. I've been using the beta release for the past couple of months and I haven't found any problems either.

Regarding a release date for v3: @syrusakbary has decided that v3 needs to include a new annotation based object type api. I don't have an ETA on when that will be implemented but I have been assured that it won't take long.

---

@hyusetiawan 

> is V3 backward compatible with third-party or even first-party plugins such as:
graphql-python/graphql-ws
tfoxy/graphene-django-optimizer
eamigo86/graphene-django-extras
?

I haven't checked that but the graphene-django-optimizer and graphene-django-extras library depend on graphene-django and the v3 release of that is tracked here: https://github.com/graphql-python/graphene-django/issues/705

Thanks for raising it though, I'll try and make sure that those libraries have been checked against v3 of graphene-django before releasing it.

**Comment by hyusetiawan** [comment]
@jkimbo I can attest that django-graphql-jwt has v3 support already merged, tested it and it has been running smoothly: https://github.com/flavors/django-graphql-jwt/pull/213

**Comment by fabienheureux** [comment]
> 
> 
> is V3 backward compatible with third-party or even first-party plugins such as:
> https://github.com/graphql-python/graphql-ws
> https://github.com/tfoxy/graphene-django-optimizer
> https://github.com/eamigo86/graphene-django-extras
> ?
> 
> Also, any guide on migration?

I started a PR for graphene-django-extras, if you want to test it https://github.com/eamigo86/graphene-django-extras/pull/148

I had no issues with django-graphql-jwt so far.

**Comment by syrusakbary** [comment]
A quick update on this. We decided to not block the release of Graphene v3 based on typing, since it might take longer than we expected. Note: the conversations are happening in Graphene Slack channel, in #graphene3-releaseplan channel.

However, we are pending to updated the GraphQL-Python Graphene dependencies (such as graphene-mongo, graphene-sqlalchemy and so) to support Graphene 3.0 and GraphQL-core 3.0.

**Comment by radekwlsk** [comment]
@jkimbo 
In release notes it should state that not

> **Misc. Changes**
> Relay's ConnectionField get_resolver function renamed to wrap_resolve

but rather 

> **Misc. Changes**
> Field get_resolver function was replaced by wrap_resolve

Also 

```
warn_deprecation(
    "The get_resolver method is being deprecated, please rename it to wrap_resolve."
)
```

should rather be in in `__init__` than `wrap_resolve`, I've spend almost an hour fixing my `PagePaginationDjangoFilterField(DjangoListFilterField)` that overwrites `get_resolve` and 

```
/home/django/venv/lib/python3.8/site-packages/graphql/type/definition.py:745: in fields
    raise TypeError(f"{self.name} fields cannot be resolved. {error}")
E   TypeError: Query fields cannot be resolved. type object 'PaginatedMyType' has no attribute 'of_type'
```
error was not really helpful. 


As a side note:
Would you be interested in PR with my `DjangoListFilterField` and `PagePaginationDjangoFilterField` that introduce `django-filters` and pagination without use of Relay?

**Comment by corydolphin** [comment]
> A quick update on this. We decided to not block the release of Graphene v3 based on typing, since it might take longer than we expected.
> 
> However, we are pending to updated the GraphQL-Python Graphene dependencies (such as, graphene-mongo  graphene-sqlalchemy and so) to support Graphene 3.0 and GraphQL-core 3.0. So, until we don't update those dependencies to support Graphene v3, we can't publish the new version.
> 
> > Note: the conversations are happening in Graphene Slack channel, in #graphene3-releaseplan channel.

Would it be possible to update those dependent packages after the release? Those libraries look to have an order of magnitude less usage. I’m sure others are anxious to update to graphene 3 and are waiting on a final release. It may also help to drive momentum and contributors to help with those extension packages’ upgrade process.

**Comment by jnak** [comment]
@syrusakbary What's the rationale for blocking the release of `graphene` on the update of dependent projects such as `graphene-sqlalchemy`? 

I'm personally in favor of releasing `graphene` as soon as it's stable and let the various projects add support at their own pace. This is a big migration for dependent packages as it implies completely dropping support for Python 2, migrating away from `promise` and `dataloader` and assuming everything now runs in an event loop. And it's probably a good moment for those packages to introduce API changes they have been pushing back for a while. I'd rather not rush maintainers to release a new version if we don't technically need to. Those projects should have all pinpointed `graphene` v2 in their requirements file there is no risk they will break when the next version of `graphene` v3.

**Comment by syrusakbary** [comment]
@jnak all projects are part of the same organization. The release process have to be uniform across projects here.

There are bunch of users of Graphene that use it with one of the integrations (Django, SQLAlchemy, ...). Doing the announcement without bringing those up to date could become a PR disaster (and normally so, as the expectations would be to be able to use at least it in the subprojects that are part of the graphql-python org).

At the same time, bringing the integrations up to date should not really take that much time. Perhaps what we need is newer maintainers of each of the subprojeects in case current ones can't not update them on a timely manner.

**Comment by noelleleigh** [comment]
Hey y'all, I'm working on making https://github.com/preply/graphene-federation compatible with v3 and I'm stuck on something:

Is there still a way to access the `auto_camelcase` attribute of a `Schema`? [Code in that project](https://github.com/preply/graphene-federation/blob/e90b2ee45c158ce0a03177d2198650e6aed24c67/graphene_federation/service.py#L67-L68) relies on that property, and I haven't found a way of accessing it after the changes made in v3.

**Comment by LaughDonor** [comment]
Oh my goodness. After several hours of painstaking research (all failed until I investigated the codebases), I've finally resolved my issue!

Setup:
> Graphene v3.0b5
> GraphQL-Server (Flask) v3.0.0b1
> Flask v1.1.2

Bare Minimum Code (following examples):
```python
from graphql_server.flask import GraphQLView
from flask import Flask
from graphene import ObjectType, Schema

class Query(ObjectType):
    pass #Class data here

app = Flask(__name__)
app.add_url_rule('/graphql', view_func=GraphQLView.as_view(
    'graphql',
    schema=schema,
    graphiql=True,
))
```

When going to the `/graphql` path, I kept getting the following error:
> AssertionError: A Schema is required to be provided to GraphQLView.

Turns out `graphene.types.schema.Schema` doesn't inherit from `graphql.type.schema.GraphQLSchema` and fails the assertion.
To fix this, I had to update the last line to pass in that stored schema to read:
```python
app.add_url_rule('/graphql', view_func=GraphQLView.as_view(
    'graphql',
    schema=schema.graphql_schema,
    graphiql=True,
))
```

Not sure if this needs to be posted on graphql-python/graphql-server#44 under Flask? The Documentation **really** needs to be clarified on this.

**Comment by klairetan** [comment]
The release notes say "when Enum's are used as an input to a field the resolver now receives the Enum member directly rather than the value". However, after testing some Enums in my code base, I found this doesn't seem to be true for Enums generated using  `graphene.Enum.from_enum`. This seems like a subtle case that might have been missed, or I might have misunderstood something?

```python
class Color(graphene.Enum):
    RED = 1
    GREEN = 2
    BLUE = 3

class ColorEnum(enum.IntEnum):
    RED = 1
    GREEN = 2


ColorGQLType = graphene.Enum.from_enum(ColorEnum)



class Query(graphene.ObjectType):
    orange = graphene.Int(input=Color(required=True),)
    apple = graphene.Int(input=ColorGQLType(required=True))

    def resolve_orange(root, info, input: Color):
        print(input)  # is Member, has name and value
        return input.name

    def resolve_apple(root, info, input: ColorGQLType):
        print(input)  # is ColorEnum.RED
        return input

schema = Schema(query=Query)
result = schema.execute(
            '''
                query {
                    orange(input: RED)
                    apple(input: RED)
               }
            ''')
```

**Comment by klairetan** [comment]
It seems like the _value_lookup code for `GraphQLEnumType` doesn't successfully a value map and only ever produces an empty Dict for `GraphQLEnumType.values`

``` python 
class GraphQLEnumType(GraphQLNamedType):
....
  @cached_property
    def _value_lookup(self) -> Dict[Any, str]:
        # use first value or name as lookup
        lookup: Dict[Any, str] = {}
        for name, enum_value in self.values.items():
            value = enum_value.value
            if value is None or value is Undefined:
                value = name
            try:
                if value not in lookup:
                    lookup[value] = name
            except TypeError:
                pass  # ignore unhashable values
        return lookup

    def serialize(self, output_value: Any) -> str:
        try:
            return self._value_lookup[output_value]
        except KeyError:  # hashable value not found
            pass
        except TypeError:  # unhashable value, we need to scan all values
            for enum_name, enum_value in self.values.items():
                if enum_value.value == output_value:
                    return enum_name
        raise GraphQLError(
            f"Enum '{self.name}' cannot represent value: {inspect(output_value)}"
        )
```
```python
class GrapheneEnumType(GrapheneGraphQLType, GraphQLEnumType):
   def serialize(self, value):
        if not isinstance(value, PyEnum):
            enum = self.graphene_type._meta.enum
            try:
                # Try and get enum by value
                value = enum(value)
            except ValueError:
                # Try and get enum by name
                try:
                    value = enum[value]
                except KeyError:
                    return Undefined
        return super(GrapheneEnumType, self).serialize(value)
```

According to the `GrapheneEnumType` serialize logic, if we return a value from our Enum field resolver that isn't a PyEnum, we end up passing a whole Enum to the serialize function in `GraphQLEnumType`. Because we've get set `enum_value.value` to be the Enum itself rather than the value, (from this line: https://github.com/graphql-python/graphene/pull/1153/files#diff-01ae69b0b701c74dcf605b179092525fL175-R175), then 
`lookup[value] = name` throws a TypeValue since it's an unhashable value. This means we usually always scan all values.

This isn't a problem itself, though likely inefficient since we could have not scanned. But if we ever pass a PyEnum in, (for example if an Enum's value is ever a PyEnum), then we pass a PyEnum in but the `self.values` map is empty and so `self._value_lookup[output_value]` in `GraphQLEnumType.serialize` throws a caught KeyError exception and the return value of the resolver is rejected.

**Comment by KingDarBoja** [comment]
Hi @LaughDonor 

Any issue regarding graphene + other server integrations should be posted on their corresponding repositories as this thread is to keep track of graphene v3 progress for release.

Also, what you been facing was already stated on the graphql-server docs -> https://github.com/graphql-python/graphql-server/blob/master/docs/flask.md#special-note-for-graphene-v3

**Comment by hyusetiawan** [comment]
just want to do a soft ping on the status of the release? I vaguely remember that it's slated to be released sometime last month? sounds like we have blockers

**Comment by KingDarBoja** [comment]
Hi @hyusetiawan 

The release is almost completed but we are waiting for some packages to update to graphql-core-3 in order to keep everything at the same version so this graphene v3 release doesn't break current libraries.

@syrusakbary @jkimbo know more abut the topic.

Cheers!

**Comment by hyusetiawan** [comment]
cc @syrusakbary  / @jkimbo  mind chiming in? sounds like we are veeery close to the finish line :)

**Comment by jkimbo** [comment]
Unfortunately I no longer have the time to work on this project so I'm going to have to bow out of this issue and let someone else finish up the v3 release. As far as I'm aware v3 is ready to be released but is blocked on the dependant libraries in the graphql-python ecosystem. I don't think there is an ETA for when those libraries will be updated.

I'll try and answer any questions here and on Slack but other than that I wish this project the best of luck. 👋

**Comment by xqzhou** [comment]
> Unfortunately I no longer have the time to work on this project so I'm going to have to bow out of this issue and let someone else finish up the v3 release. As far as I'm aware v3 is ready to be released but is blocked on the dependant libraries in the graphql-python ecosystem. I don't think there is an ETA for when those libraries will be updated.
> 
> I'll try and answer any questions here and on Slack but other than that I wish this project the best of luck. 👋

What dependent libraries are blocking the release?

**Comment by DoctorJohn** [comment]
@xqzhou Here's a little overview. 

| Library  | Status | Issue / PR | 
|---|---|---|
| graphene-django | A v3 branch is ready | [Issue](https://github.com/graphql-python/graphene-django/issues/705) |
| graphene-gae | This lib is deprecated | - |
| graphene-mongo | v3 PR present | [Issue](https://github.com/graphql-python/graphene-mongo/issues/154), [PR](https://github.com/graphql-python/graphene-mongo/pull/155) |
| graphene-pydantic | Version based on v3 just released | [Issue](https://github.com/graphql-python/graphene-pydantic/issues/36), [PR](https://github.com/graphql-python/graphene-pydantic/pull/45) |
| graphene-sqlalchemy | Still on v2 | [Issue](https://github.com/graphql-python/graphene-sqlalchemy/issues/248) |
| graphene-tornado | Already based on v3  | - |

**Comment by skewty** [comment]
`__init__.py` says beta 6 yet `setup.py` still stays alpha as per issue #1248.

**Comment by Speedy1991** [comment]
@DoctorJohn Can you update the table please? `graphene-django` just switched to the `main` branch with support for v3

Also pydantic looks [finished](https://github.com/graphql-python/graphene-pydantic/pull/45)

Looks like only mongo (not started) and sqlalchemy (WIP) is missing?

**Comment by radekwlsk** [comment]
Can I somehow help to push `graphene` v3 release through? It's been over a year already.

**Comment by DoctorJohn** [comment]
@radekwlsk You could help porting the sqlalchemy and mongo integrations to v3. I tried porting graphene-mongo a while ago but didn't manage to finish it. Unfortunately I don't have time to work on graphene at the moment.

**Comment by radekwlsk** [comment]
Do we really need to port all libraries that depend on `graphene`? It is not like `graphene` needs them, they need it and should pin version to `graphene<3`, for me ensuring that it is there would be enough of a "port".

**Comment by nikolaik** [comment]
The two remaining libraries that that do not yet support v3, both have `graphene<3` in `install_requires`
- [graphene-mongo](https://github.com/graphql-python/graphene-mongo/blob/ff387fec3a233e8bd6b43d79fd18c4f6f33c0d48/setup.py#L27)
- [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy/blob/7a48d3dd6b297c6d13d01df1f268a16e52f3deb0/setup.py#L16)

**Comment by AntonOfTheWoods** [comment]
@DoctorJohn, now that @jkimbo apparently is not driving the release process, are you the release owner? I certainly understand the desire to have a coordinated release but (apparently) the two remaining haven't had new releases in many months now (almost a year soon) and there are other, non-`graphql-python` downstream projects that are blocking on this project releasing v3. As @nikolaik mentions, the two projects have pinned `graphene<3`, and I'm not sure that the publicity problem would be huge. In fact, releasing v3 might actually be a good boost and motivate those projects to update?

**Comment by DoctorJohn** [comment]
@anisjonischkeit I totally agree with you. Unfortunately I'm just another contributor who tried to push this release. The decision to do a coordinated release originated in these comments (https://github.com/graphql-python/graphene/issues/1127#issuecomment-670318972, https://github.com/graphql-python/graphene/issues/1127#issuecomment-682594607) by the original graphene author. I would have published graphene v3 already if it were my decision.

**Comment by AntonOfTheWoods** [comment]
Thanks @DoctorJohn , actually, I don't really have an investment in this yet, so like many others who need modern GraphQL support, I started looking at `strawberry`. Considering I also need django and subscriptions, and they are only supported via an external module, this definitely makes graphene less appealing than `strawberry`. I tried to get things (django + subscriptions) working on strawberry, couldn't, and within a couple of hours the maintainer had posted a fully working example with the gotchas spelled out. But I'm sure there are lots of others like me, so I suppose there must be a different reason that they don't want to communicate about (other than "bad publicity" because all this looks like much worse publicity in my mind...).

**Comment by jkimbo** [comment]
@AntonOfTheWoods I share your frustration that Graphene v3 still hasn't been released because @syrusakbary wants all the dependant libraries to be updated at the same time. If it wasn't for that v3 could have been released 6 months ago. That is partly why I decided to step away from maintaining Graphene and I have since migrated my projects to use strawberry (which I would highly recommend).

Frankly at this point the best thing for this library would be for @syrusakbary to unblock this release and let v3 be released so that things can move forward.

**Comment by AntonOfTheWoods** [comment]
Thanks @jkimbo , I pretty much have a `strawberry` version of things working now. Open source project management is a complex business, and I guess sometimes you have goals that will alienate a portion of your (potential) users. Anyway, we have `strawberry`, which I agree is awesome, so I guess everyone is happy?

**Comment by mjmonroe** [comment]
We are also moving away from Graphene because it has taken soooo long for v3 support to be released. Our team decided on [ariadne](https://ariadnegraphql.org/) over [strawberry](https://github.com/strawberry-graphql/strawberry). I see no reason to block Graphene v3 if related libraries have been pinned to v2.

**Comment by jkimbo** [comment]
Btw I've created a call for maintainers issue to try and find some people with the time to look after Graphene and push it forward: https://github.com/graphql-python/graphene/issues/1312

It would be a shame if Graphene was to stagnate because I know a lot of people use it and migrating to another library is not always an option.

**Comment by cj-lin** [comment]
We decided not to migrate to [new modules](https://graphql.org/code/#python) so early because (we think) they are not as mature as `Graphene`.

Still looking forward to it being updated as soon as possible.

**Comment by keithhackbarth** [comment]
@syrusakbary - Any updates here? 

Graphene is an amazing library and we are truly thankful for everything you all have created. The community, including myself, would love to do our part in contributing and making sure it continues. However, I feel as though reading the comments above and in other threads - that there's a growing perception (right or wrong) that graphene is no longer maintained. And we would love to hear your thoughts.

From what I can tell, the two most actively used libraries `graphene` and `graphene-django` are both ready to ship, so why not ship them and let the community pick up the slack for other smaller less used libraries? For example, if I was using mongo, then I would at least have options (pinning to v2 or contributing to get up to v3).

Ain't you worried that the whole ecosystem might start fragmenting and/or dying if there are no official releases in almost 2 years? That seems like a much higher risk than releasing v3 without mongo/sqlalchemy support.

**Comment by syrusakbary** [comment]
Hi @keithhackbarth! thanks for the ping.

I've been focusing on other venture of mine this last years, which had unintended consequences. But the truth is that I still have big goals for Graphene. And I'll do whatever is in my hand to make it shine to the level it can.
I personally apologize for not caring care of the project as much as I should have (sometimes is challenging to do it while creating a company, talking with investors and managing teams).

I'd like to do a few things to empower the ecosystem:
* Release Graphene v3 very soon (so it doesn't stagnate)
* Add typing support to Graphene
* Add more part-time maintainers into the project
* Setup again a Github sponsors model. I'll make sure if we reach a $5-10k goal to employ a person that I trust to maintain the package in the same way (and hopefully even better) I would done myself

Let me know if you have more ideas about it!

**Comment by jkimbo** [comment]
@syrusakbary can you take over https://github.com/graphql-python/graphene/issues/1312 then please? There is some interest from people to help out but if you can organise it that would be helpful.

**Comment by matteing** [comment]
@syrusakbary Thanks for your ongoing support and, regarding your ventures, best!

**Comment by JBrVJxsc** [comment]
Need v3 here... v2 is extremely slow

**Comment by RainshawGao** [comment]
two months go, any update?

**Comment by matteing** [comment]
Project is basically dead.

Sent from my iPad

On Jun 2, 2021, at 3:14 AM, Rainshaw ***@***.***> wrote:

﻿

two months go, any update?

**Comment by SaschaKrug** [comment]
So, no "no, no, no we haven't abandoned this project!". Even after a month? That's really sad. I was really hoping I could skip REST for my next project

**Comment by mjmonroe** [comment]
@SaschaKrug, [Ariadne](https://ariadnegraphql.org/) and [Strawberry](https://strawberry.rocks/) are similar projects, both well supported by the open source community.  Like Graphene v3, they both use graphql-core v3.1. We are switching our new services to Ariadne from Graphene v2.

**Comment by Speedy1991** [comment]
I know this is not a fix for the graphene users, but:

The [strawberry](https://github.com/strawberry-graphql/strawberry) community is really active and helpful! If you are familiar with python dataclasses, the port is straightforward and easy because you can keep your whole business logic from the resolvers and just change the wrapping gql code.

To verify a successful port, you can compare the generated schemas.

**Comment by richin13** [comment]
> Hi @keithhackbarth! thanks for the ping.
> 
> I've been focusing on other venture of mine this last years, which had unintended consequences. But the truth is that I still have big goals for Graphene. And I'll do whatever is in my hand to make it shine to the level it can.
> I personally apologize for not caring care of the project as much as I should have (sometimes is challenging to do it while creating a company, talking with investors and managing teams).
> 
> I'd like to do a few things to empower the ecosystem:
> 
>     * Release Graphene v3 very soon (so it doesn't stagnate)
> 
>     * Add typing support to Graphene
> 
>     * Add more part-time maintainers into the project
> 
>     * Setup again a Github sponsors model. I'll make sure if we reach a $5-10k goal to employ a person that I trust to maintain the package in the same way (and hopefully even better) I would done myself
> 
> 
> Let me know if you have more ideas about it!

The best thing you can do is move away from this project a let other people take over as it is clear you're problem here.

**Comment by keithhackbarth** [comment]
@syrusakbary - Any updates here? If you want to make me an admin of this repo, I'd be happy to manage a v3 release.

@jkimbo - Do you have the ability to roll a v3 release? It seems like you were able to do the alpha releases.

I would really love to keep this repo alive!

**Comment by jkimbo** [comment]
@keithhackbarth : @syrusakbary has previously said that he doesn't want to release v3 until all dependant libraries have been updated: https://github.com/graphql-python/graphene/issues/1127#issuecomment-670318972 and I'm not sure what the progress of that is. 

Also I'm not comfortable pushing a new version (which will probably have some teething problems) while not being an active maintainer of the project.

**Comment by cpontvieux-systra** [comment]
Up ?

**Comment by mvanlonden** [comment]
We're almost there! Two more graphene libraries need to support v3, [graphene-sqlalchemy](https://github.com/graphql-python/graphene-sqlalchemy) to v3 [WIP](https://github.com/graphql-python/graphene-sqlalchemy/pull/306) and [graphene-mongo](https://github.com/graphql-python/graphene-mongo) to v3 [WIP](https://github.com/graphql-python/graphene-mongo/pull/155). If we can get tests passing on these last two PRs, we can release graphene v3.

@DoctorJohn and @zsiciarz can you bring us over the finish line? Any blockers on your current WIP PRs? @jetzhou also offered to help with the sqlalchemy upgrade. @jetzhou can you work with @zsiciarz to bring [this PR](https://github.com/graphql-python/graphene-sqlalchemy/pull/306) home?

**Comment by richin13** [comment]
Actually `graphene-mongo` was migrated to v3 (https://github.com/graphql-python/graphene-mongo/blob/98f2929956d199ab4c11f8db5f9bdbf361a70bbc/setup.py#L25) and has all its tests passing. (Unless I'm missing something?? 😅 )

It's only `graphene-sqlalchemy` at this point, for which PR https://github.com/graphql-python/graphene-sqlalchemy/pull/317 exists (fixes all broken tests). We just need to have https://github.com/graphql-python/graphene-sqlalchemy/pull/316 merged so that we can run the tests against the PR (Travis is broken)

**Comment by keithhackbarth** [comment]
Is there a reason we don't just don't let the downstream repositories manage their own dependencies and upgrade at their leisure? Isn't that why each repo has its own requirements file - so they can pin to v2 if they aren't ready to upgrade? I can't think of any other codebase in the python ecosystem that requires all of its downstream repositories to upgrade before the official version of the upstream one gets released. Does anyone have an example of this? It feels very "cart before the horse", no?

**Comment by pappasam** [comment]
@keithhackbarth let's answer this question once v3 is actually released. @richin13 and others have jumped through flaming hoops, so let's not let a potential flame war slow things down!

**Comment by AntonOfTheWoods** [comment]
@pappasam , "slow things down". Really? It is probably mathematically impossible to go any slower than this issue has been managed. It will soon be multiple YEARS since this repo has been waiting for the downstream repos to confirm compatibility.

**Comment by McPo** [comment]
> Is there a reason we don't just don't let the downstream repositories manage their own dependencies and upgrade at their leisure? Isn't that why each repo has its own requirements file - so they can pin to v2 if they aren't ready to upgrade? I can't think of any other codebase in the python ecosystem that requires all of its downstream repositories to upgrade before the official version of the upstream one gets released. Does anyone have an example of this? It feels very "cart before the horse", no?

I 1000% agree. Theres also little motivation for the other projects to upgrade if they are still technically on the stable build.

As they get left behind, they may be more likely to get up to speed. And if they don't then they don't have the userbase to warrant the effort.

Contributors are also more likely to help when they see that an actual release has occured. There's simply no way Id dedicate any of my time to this project simply because it's in release hell. Sure it's inching ever so slowly, but Im more likely to contribute to a OSS (and thus get the child dependencies up to speed quicker), if I can see quick returns on my effort. Not taking years to release.

BTW I'm not even that motivated for a new release of this project, as I've since moved on. So if this is coming across as abrupt then I do apologise, it's definitely not meant that way. However I do think who ever decided such a policy needs to seriously rethink it. I feel it stifles any incentive in getting involved in the project, and simply grinds it to a halt. Move on and let the dependencies catch up.

**Comment by mark7-bell** [comment]
We need to assess whether v3 addresses performance problems we are seeing, or we need to find another technology soon.

**Comment by JBrVJxsc** [comment]
> We need to assess whether v3 addresses performance problems we are seeing, or we need to find another technology soon.

v3 uses native asyncio instead of the Promise libraries that are being used by v2.
v3 should be a lot faster than v2.

however, we are waiting for v3 for soooo long.

**Comment by mvanlonden** [comment]
With the [release of v3 graphene-sqlalchemy](https://pypi.org/project/graphene-sqlalchemy/3.0.0b1/), all dependent libraries now support v3. This unblocks the release of v3!

**Comment by lovetoburnswhen** [comment]
> With the [release of v3 graphene-sqlalchemy](https://pypi.org/project/graphene-sqlalchemy/3.0.0b1/), all dependent libraries now support v3. This unblocks the release of v3!

at long last

**Comment by AntonOfTheWoods** [comment]
The cows have come home!!!!!

**Comment by colelin26** [comment]
> With the [release of v3 graphene-sqlalchemy](https://pypi.org/project/graphene-sqlalchemy/3.0.0b1/), all dependent libraries now support v3. This unblocks the release of v3!

Thanks for the fast code review and release for us! Glad to see that my code was able to help :) I think it really shows that a lot of us from the community are willing to help and how important Graphene is to us.

**Comment by tstordyallison** [comment]
What are next steps for cutting a release? Looks like all the downstream libraries are ready.

**Comment by cglacet** [comment]
@tstordyallison according to the checklist the last point is supposed to be checked by [this merge](https://github.com/graphql-python/graphene-mongo/pull/172)?

**Comment by Birdi7** [comment]
@jkimbo @ekampf hello! do you have any thoughts on releasing v3.0?

**Comment by mvanlonden** [comment]
Cut v3.0.0 today

https://github.com/graphql-python/graphene/releases/tag/v3.0.0

**Comment by felixmeziere** [comment]
@syrusakbary any progress with this https://github.com/graphql-python/graphene/issues/1127#issuecomment-806119584 ? ... :/

**Comment by kubami** [comment]
What is the outstanding tasks to releasing the v3? All the TODO items have been checked off. I have been using the 3.0.0b7 for a year now.

**Comment by flbraun** [comment]
@kubami Graphene v3 has already been released on Nov 13 2021 (see [PyPI](https://pypi.org/project/graphene/#history)). Not sure what you're after?

**Comment by aryadovoy** [comment]
What about `UPGRADE-v3.0.md`?

**Comment by jkimbo** [comment]
@aryadovoy the release notes for v3 should cover all the changes you need to make: https://github.com/graphql-python/graphene/wiki/v3-release-notes
